### PR TITLE
faster construction, some fixes and other optimizatioons

### PR DESCRIPTION
**Pull request by karasikov**

### CODE REVIEW

**Comment by nicolaprezza** [comment]
Thanks Mikhail for the remarkable work! Sorry for the delayed response, I've been quite busy in the last few weeks. 

I'm running some tests to compare the current version with yours. One question: it seems that you are working on parallel wavelet tree construction? what is the status on this new development?

Nicola

**Comment by karasikov** [comment]
Hi Nicola,

Thanks for merging.

> One question: it seems that you are working on parallel wavelet tree construction? what is the status on this new development?

Yes, we implemented a simple parallelized function for extending a wavelet tree with a batch in [push_many](https://github.com/xxsds/DYNAMIC/blob/1b9105f2e59ec5104c599244cb9841a14d2b820a/include/internal/wt_string.hpp#L421).
This function is used in constructor `wt_string(uint64_t sigma, const t_str& str)`, so this may be used as a fast parallel constructor.

**Comment by nicolaprezza** [comment]
I see, nice job! many thanks for the effort.

**Comment by nicolaprezza** [comment]
Hi Mikhail, 

I just fixed two bugs in your optimizations, both in packed_vector:

- in the instruction "std::copy(&words[nr_left_words], &words[tot_words], right_words.begin())";, the access words[tot_words] was causing an out-of-range error when tot_words was equal to words' size. I replaced it using words.begin() + tot_words.
- in "falling_out = (words[current_word] >> (int_per_word_-1)*width_);", you forgot to mask the result: in some cases, this instruction was returning an integer with more than width_ bits. Note that the function at() (which you replaced with the above line) always masks the result.

I just spotted these errors by running the test algorithms cw-bwt and rle_bwt with asserts enabled (but somehow I missed them when I tested your modifications before merging). Please, if you implement other optimization, could you run extensive tests with asserts enabled before pushing? Thanks!

**Comment by karasikov** [comment]
Hi Nicola,

Thanks a lot!

**Pull request merged**
