### PR TITLE
mmmulti requesting vgteam's DYNAMIC clone - what should Debian do?

### PR DESCRIPTION
**Pull request by smoe**
Hello,

DYNAMIC is a dependency of mmmulti (https://github.com/ekg/mmmulti/search?q=DYNAMIC&unscoped_q=DYNAMIC) which in turn is required as a dependency for seqwish which is referenced by a few workflows for Nanopore sequencing data, which we address as part fo the Covid-19 hackathon. Now, mmmulti explicitly references to a fork of yours (https://github.com/vgteam/DYNAMIC.git) to which then the author of mmmulti (@ekg) contributes.

This is a bit of a dilemma for the Linux distributions who tend to avoid shipping multiple versions of the same software. Preferably we would take the original, but if a change is important for the reverse dependency, then it is the fork that would be packaged. It is a bit weird that I now create a pull request even though I don't contribute to DYNAMIC at all. But since I could not place an issue with the vgteam's fork about it, and this button popped up suggesting a pull request - please forgive.

Please kindly comment on what would be the right thing for Debian to do. 

Many thanks!

Steffen

### CODE REVIEW

**Comment by ekg** [comment]
We should merge into upstream DYNAMIC.

**Comment by nicolaprezza** [comment]
@ekg, you mean merging vgteam's DYNAMIC into upstream? fine to me, can you take care of it? (I think you should have all the permissions)

**Comment by ekg** [comment]
Yeah, I think so. I'll dissect the differences. I don't think it's much.

**Comment by smoe** [comment]
Happy about the progress. A look at https://github.com/xxsds/DYNAMIC/compare/master...ekg:master suggests that there is nothing left to pull. Someone with more insights than me please then close this PR.

As a bit of a related request - would this merger possibly warrant a release tag?

Thank you all!
Steffen

**Comment by nicolaprezza** [comment]
PR closed. We're currently adding new features and slightly refactoring the library in the process to publish a journal paper about it. We'll create release 1 after that. 

thanks for your interest in the library!
Nicola

**Comment by smoe** [comment]
@nicolaprezza Have many thanks for all your support. Just to explain what I had meant with "release" - it is just a tag that gives your commits some linear structure as in "everything after this can be used with vgteam with no prob". Nothing to officially celebrate as a 1.0 release. It is very common to start with a release 0.0. The motivation to have releases for you would be to tell your reverse dependencies that your refacturing (with a chance to break the A[BP]I) has not happened, yet. For the refactored code base you would then jump to 0.99 or 1.0~alpha.1 and once your paper is accepted release the 1.0.

For now we just need to have some sort of version on our side that will then be substituted with whatever you eventually release as a release. Our side's default for untagged (sounds bettern than unreleased, maybe) software is something much like 0.0~ day+gittag, i.e.  "0.0~20200716+gitb11d42b". 

Cheers,
Steffen

**Comment by nicolaprezza** [comment]
Hi Steffen, I created a first pre-release. The code is already stable and we don't have much refactoring to do, so it's already pre-release 1.0-alpha. We'll release the 1.0 after the paper is published.

cheers, 
Nicola

**Pull request merged**
